---
- name: Install k9s on CentOS via Snap
  hosts: masters  # Adjust as needed
  become: yes
  tasks:
    - name: Install EPEL repository
      shell: yum install -y epel-release

    - name: Install snapd
      shell: yum install -y snapd

    - name: Enable and start snapd.socket
      shell: systemctl enable --now snapd.socket

    - name: Create a symlink for snap
      shell: |
        if [ ! -d /snap ]; then
          ln -s /var/lib/snapd/snap /snap
        fi

    - name: Wait for snapd to initialize
      pause:
        seconds: 20

    - name: Install k9s via Snap
      shell: snap install k9s

    - name: Verify k9s installation
      shell: k9s version
      register: k9s_version
      ignore_errors: yes

    - name: Show k9s version
      debug:
        var: k9s_version.stdout
