---
- name: Install k9s on CentOS
  hosts: masters  # Adjust this as needed
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - curl
          - tar
        state: latest

    - name: Download k9s binary
      shell: |
        curl -sSL -o /tmp/k9s.tar.gz https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_x86_64.tar.gz

    - name: Check downloaded file type
      command: file /tmp/k9s.tar.gz
      register: file_type

    - name: Fail if the file is not a valid gzip
      fail:
        msg: "Downloaded file is not a valid gzip format. Check the download URL."
      when: "'gzip compressed data' not in file_type.stdout"

    - name: Extract k9s binary
      shell: |
        tar -xzf /tmp/k9s.tar.gz -C /usr/local/bin
        chmod +x /usr/local/bin/k9s

    - name: Verify k9s installation
      shell: k9s version
      register: k9s_version
      ignore_errors: yes

    - name: Show k9s version
      debug:
        var: k9s_version.stdout
